---
title: "Exercise_3"
author: "Mathujah Manikkan"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages 
```{r message=FALSE, warning=FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(SimilarityMeasures)
library(tidyr)
```

## Implement file(s)
```{r warning=FALSE}
caro <- read_delim("caro60.csv")

```

## Step a): Specify a temporal window v
### The sampling interval for this dataset is 1 minute. Use a temporal window v of 6 minutes, i.e. a window size of 6 positions (n±3).

1. pos[n-3] to pos[n]
2. pos[n-2] to pos[n]
3. pos[n-1] to pos[n]
4. pos[n] to pos[n+1]
5. pos[n] to pos[n+2]
6. pos[n] to pos[n+3]

```{r warning=FALSE}
caro <- caro %>%
  mutate(
    nMinus3 = sqrt((lag(E,3)-E)^2+(lag(N,3)-N)^2),   # distance to pos -3 minutes
    nMinus2 = sqrt((lag(E,2)-E)^2+(lag(N,2)-N)^2),   # distance to pos -2 minutes
    nMinus1 = sqrt((lag(E,1)-E)^2+(lag(N,1)-N)^2),   # distance to pos -1 minute
    nPlus1  = sqrt((E-lead(E,1))^2+(N-lead(N,1))^2), # distance to pos +1 mintue
    nPlus2  = sqrt((E-lead(E,2))^2+(N-lead(N,2))^2), # distance to pos +2 minutes
    nPlus3  = sqrt((E-lead(E,3))^2+(N-lead(N,3))^2)  # distance to pos +3 minutes
  )

```
